### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by Firefishy** [pgporada/terraform-makefile#1]
Very nice Makefile. I'd like to use it for an internal project...

The `README.md` has (C), but under what license it the code released?

My personal favourite licenses are:
- https://opensource.org/licenses/ISC
- http://www.wtfpl.net/

**Comment by pgporada** [comment]
As soon as I get into work I'll take a look. Thanks for your support!

**Comment by pgporada** [comment]
I'm going to be applying the Apache 2.0 license. I'm currently in the process of updating the Makefile.

**Comment by pgporada** [comment]
@Firefishy

**Comment by Firefishy** [comment]
👍
