### ISSUE TITLE
make: *** [prep] Error 255

### ISSUE THREAD

**Issue by seanoreilly1973** [pgporada/terraform-makefile#3]
If a bucket doesn't exist awscli returns a 255 exit code. I am assuming that make isn't handling this properly and just failing rather than continuing on and  creating the bucket as expected.

I can't get the Makefile to work because of this issue. Any help would be appreciated.

ps This only appears to happen on OS X

**Comment by pgporada** [comment]
@seanoreilly1973 Can you try installing gmake (gnu make) and seeing if the same thing happens? Sorry for the delay in response. I don't have a mac to test this on.

**Comment by avoidik** [comment]
https://github.com/pgporada/terraform-makefile/pull/5 addressed this issue

**Comment by pgporada** [comment]
#5 was merged. @seanoreilly1973  if you still happen to use terraform and this makefile, mind giving it another test? I don't have an OSX install.
